PROGRAM =  
LIBS = 
LIBDIRS = 
INCDIRS = 

#change to -ggdb for debugging -o2 for release
COMPILER = g++
COMPILEFLAGS = -ggdb
COMPILE = $(COMPILER) $(COMPILEFLAGS)

CLI_FILENAME = 
CLI_SOURCES = $(CLI_FILENAME).cpp 
CLI_OBJFILE = $(CLI_FILENAME).o 

SRV_FILENAME = 
SRV_SOURCES = $(SRV_FILENAME).cpp
SRV_OBJFILE = $(SRV_FILENAME).o

all: $(CLI_FILENAME) $(SRV_FILENAME)

$(CLI_FILENAME): $(CLI_OBJFILE) 
	$(COMPILE) -o $(CLI_FILENAME) $(foreach incdir,$(INCDIRS),-I$(incdir)) $(CLI_OBJFILE) $(foreach slib,$(LIBS), -l$(slib) )

$(SRV_FILENAME): $(SRV_OBJFILE)
	$(COMPILE) -o $(SRV_FILENAME) $(foreach incdir,$(INCDIRS),-I$(incdir)) $(SRV_OBJFILE) $(foreach slib,$(LIBS), -l$(slib) )

$(CLI_OBJFILE): $(CLI_SOURCES)
	$(COMPILE) -c $(CLI_SOURCES)

$(SRV_OBJFILE): $(SRV_SOURCES)
	$(COMPILE) -c $(SRV_SOURCES)

# abstract (phony) targets
.PHONY: clean
clean:
	rm -rf $(SRV_FILENAME) $(CLI_FILENAME) $(CLI_OBJFILES) $(SRV_OBJFILES)

.PHONY: rebuild
rebuild: clean all

